model:
  name: philschmid/bart-large-cnn-samsum
  padding: true
  truncation: true
  min_length: 20
  max_length: 150

mlflow:
  tracking_uri: https://dagshub.com/dimoynwa/sp2t-text-summarizer.mlflow
  # tracking_uri: http://localhost:5000
  local_dir: mlflow/models
  log_model: true
  save_model: false
  registered_model_name: text_summarization

dagshub:
  user: dimoynwa
  repo: sp2t-text-summarizer

data:
  clean_data_dir: dataset/cleaned
  summaries_dir: dataset/summaries